# Generated by Django 3.0.8 on 2020-07-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franciscan_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
